kind = "api"
previewPath = "/api-backend/"
title = "Novadent"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3001
name = "API Server"
paths = ["/api-backend/"]

[services.development]
run = "cd /home/runner/workspace/novadent/backend && NODE_ENV=production node dist/src/main.js"

[services.production]

[services.production.build]
args = ["bash", "-c", "cd /home/runner/workspace/novadent && npm run build && cd /home/runner/workspace/novadent/backend && NODE_ENV=development ./node_modules/.bin/nest build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "novadent/backend/dist/src/main.js"]

[services.production.run.env]
PORT = "3001"
NODE_ENV = "production"
